// Auto-converted from Stitch export. Raw HTML preserved via dangerouslySetInnerHTML
// so nothing breaks during conversion (SVG attrs, inline styles, etc).
// TODO (next pass, ideally with Claude Code + full repo access): refactor into real
// componentized JSX, wire data-* attributes to real hooks (useProducts, useCart, etc),
// remove dangerouslySetInnerHTML once componentized.
export default function NotFound() {
  return (
    <div
      dangerouslySetInnerHTML={{ __html: "\n\n\n\n<main class=\"flex-grow flex items-center justify-center px-margin-mobile md:px-margin-desktop py-section-gap-lg\">\n<div class=\"max-w-2xl w-full text-center fade-in\">\n\n<div class=\"mb-8\">\n<h1 class=\"font-display-lg text-[120px] md:text-[180px] leading-none text-primary/20 select-none\">\n                    404\n                </h1>\n</div>\n\n<div class=\"space-y-6\">\n<div class=\"space-y-2\">\n<p class=\"font-label-caps text-label-caps text-secondary tracking-[0.2em] uppercase\">\n                        PAGE NOT FOUND\n                    </p>\n<h2 class=\"font-display-lg text-display-lg-mobile md:text-display-lg text-on-surface\">\n                        This page has wandered off\n                    </h2>\n</div>\n<p class=\"font-body-lg text-body-lg text-on-surface-variant max-w-md mx-auto\">\n                    Even the finest treasures can sometimes be misplaced. Let us guide you back to our curation.\n                </p>\n\n<div class=\"pt-8\">\n<a class=\"inline-block bg-primary-container text-on-primary font-button-text text-button-text px-10 py-4 rounded-none hover:scale-[1.02] transition-transform duration-300 active:bg-primary\" href=\"/\">\n                        RETURN TO SHOP\n                    </a>\n</div>\n</div>\n\n<div class=\"mt-16 flex justify-center\">\n<div class=\"w-16 h-[1px] bg-outline-variant/60\"></div>\n</div>\n</div>\n</main>\n\n\n<script>\n        // Subtle Parallax Effect for the heritage background\n        document.addEventListener('mousemove', (e) => {\n            const moveX = (e.clientX - window.innerWidth / 2) * 0.01;\n            const moveY = (e.clientY - window.innerHeight / 2) * 0.01;\n            const bg = document.body;\n            // Accessing the pseudo-element directly isn't possible, so we shift a wrapper if needed.\n            // For simplicity in this single-page design, we'll keep the static feel as requested \"Quiet Luxury\".\n        });\n    </script>\n" }}
    />
  );
}
